from __future__ import annotations

import json
import shutil
from pathlib import Path

from PIL import Image

from .reconstruction import reconstruct_mock_bev
from .traversability_model import discover_image_label_pairs


def _copy_as_png(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.suffix.lower() == ".png":
        shutil.copy2(src, dst)
        return
    Image.open(src).convert("RGB").save(dst)


def import_rugd_sequence(
    source_root: Path,
    target_data_root: Path,
    *,
    sequence_id: str = "rugd_mini",
    max_samples: int = 24,
    overwrite: bool = True,
) -> dict[str, object]:
    pairs = discover_image_label_pairs(source_root, max_samples=max_samples)
    if not pairs:
        raise FileNotFoundError(f"No RUGD-style image/label pairs found under {source_root}")

    sequence_dir = target_data_root / "sequences" / sequence_id
    if sequence_dir.exists() and overwrite:
        shutil.rmtree(sequence_dir)
    (sequence_dir / "images").mkdir(parents=True, exist_ok=True)
    (sequence_dir / "labels").mkdir(parents=True, exist_ok=True)
    (sequence_dir / "lidar").mkdir(parents=True, exist_ok=True)
    (sequence_dir / "occupancy").mkdir(parents=True, exist_ok=True)

    manifest: list[dict[str, str]] = []
    for index, (image_path, label_path) in enumerate(pairs):
        image_dst = sequence_dir / "images" / f"frame_{index:04d}.png"
        label_dst = sequence_dir / "labels" / f"semantic_{index:04d}.png"
        _copy_as_png(image_path, image_dst)
        _copy_as_png(label_path, label_dst)
        manifest.append(
            {
                "frame": f"frame_{index:04d}",
                "source_image": str(image_path),
                "source_label": str(label_path),
                "image": str(image_dst.relative_to(sequence_dir)),
                "label": str(label_dst.relative_to(sequence_dir)),
            }
        )

    reconstruct_mock_bev(sequence_dir / "occupancy", seed=43, terrain="gravel")

    poses = ["timestamp,x,y,z,yaw,pitch,roll,speed"]
    for index in range(len(pairs)):
        poses.append(f"{index * 0.1:.1f},{index * 1.25:.3f},0.0,0.0,0.0,0.03,0.0,4.2")
    (sequence_dir / "poses.csv").write_text("\n".join(poses) + "\n", encoding="utf-8")
    (sequence_dir / "calibration.json").write_text(
        json.dumps(
            {
                "camera": {"width": 0, "height": 0, "fx": None, "fy": None, "cx": None, "cy": None},
                "note": "Imported from RUGD-style RGB/semantic pairs; calibration unknown.",
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    metadata = {
        "scene_id": sequence_id,
        "terrain": "gravel",
        "weather": "sunny",
        "time_of_day": "day",
        "difficulty": "real-data",
        "tags": ["rugd", "public-dataset", "semantic-segmentation", "unstructured-road"],
        "has_lidar": False,
        "has_occupancy": True,
        "vehicle_id": "ugv_default",
    }
    (sequence_dir / "metadata.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
    (sequence_dir / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    source_card = {
        "sequence_id": sequence_id,
        "dataset_name": "RUGD-style public semantic dataset import",
        "source_type": "public",
        "license": "Check the original RUGD dataset license/terms before redistribution.",
        "citation": "RUGD: Robot Unstructured Ground Driving dataset. Cite the original RUGD dataset/paper/site.",
        "homepage": "https://rugd.vision/",
        "importer": "ml.rugd_adapter.import_rugd_sequence",
        "importer_version": "orwm-rugd-importer-v0.1",
        "source_root": str(source_root),
        "target_root": str(sequence_dir),
        "manifest_path": str(sequence_dir / "manifest.json"),
        "sensors": ["front_rgb", "semantic_mask", "occupancy_or_bev", "placeholder_pose"],
        "tags": metadata["tags"],
        "known_limitations": [
            "No LiDAR/depth/action stream in the current RUGD-style import.",
            "poses.csv is a placeholder straight-line pose stream.",
            "calibration.json is unknown/placeholder.",
            "occupancy maps are generated by OR-WM mock BEV reconstruction.",
        ],
        "recommended_next": [
            "Use this source for terrain perception and label remapping.",
            "Use TartanDrive-style data for real trajectory prediction.",
            "Use RELLIS-3D-style data for LiDAR BEV reconstruction.",
        ],
    }
    (sequence_dir / "source_card.json").write_text(json.dumps(source_card, ensure_ascii=False, indent=2), encoding="utf-8")
    return {
        "sequence_id": sequence_id,
        "source_root": str(source_root),
        "target_root": str(sequence_dir),
        "imported_frames": len(pairs),
        "manifest": str(sequence_dir / "manifest.json"),
    }
